name: Test

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16_Release_Candidate.app

    steps:
    - name: Show environments
      run: |
        xcodebuild -version
        swift --version
    - name: Checkout
      uses: actions/checkout@v4
      with:
          submodules: true
          fetch-depth: 0
    - name: Unit Test for EditorCore
      run: |
        swift test --package-path Packages/EditorCore  --quiet
    - name: Unit Test for MacUI
      run: |
        swift test --package-path Packages/MacUI  --quiet
    - name: Unit Test for SyntaxMap
      run: |
        swift test --package-path Packages/SyntaxMap  --quiet
    - name: Unit Test for CotEditor
      run: |
        xcodebuild test -project CotEditor.xcodeproj -scheme CotEditor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -skipPackagePluginValidation
