name: Test

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16_beta_6.app

    steps:
    - name: Show environments
      run: |
        xcodebuild -version
        swift --version
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: |
        git submodule update --init
    - name: Unit Test for EditorCore
      run: |
        swift test --package-path Packages/EditorCore  --quiet
    - name: Unit Test for MacUI
      run: |
        swift test --package-path Packages/MacUI  --quiet
    - name: Unit Test for SyntaxMap
      run: |
        swift test --package-path Packages/SyntaxMap  --quiet
    - name: Unit Test for CotEditor
      run: |
        xcodebuild test -project CotEditor.xcodeproj -scheme CotEditor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -skipPackagePluginValidation
